version: '3.8'

services:
  api_gateway:
    build: ./API_gateway
    ports:
      - "8000:8000"
    environment:
      - INTERNAL_SECURITY=HTTP #Switch HTTP/HTTPS for hybrid/traditional architecture
      - SECRET_KEY=secret
    networks:
      - micro_network
    deploy:
      resources:
        limits:
          cpus: 0.50  # Resource limit for stable measurements

  auth_service:
    build: ./auth_service
    networks:
      - micro_network
    deploy:
      resources:
        limits:
          cpus: '0.50'

  user_service:
    build: ./user_service
    # No ports resulting in no way in
    networks:
      - micro_network
    deploy:
      resources:
        limits:
          cpus: '0.50'

  data_service:
    build: ./data_service
    networks:
      - micro_network
    deploy:
      resources:
        limits:
          cpus: '0.50'

networks:
  micro_network:
    driver: bridge